-- ######################
-- ## Field quantities ##
-- ######################

-- Production rates
FOPR
FGPR
FWPR
FLPR
FVPR
FOPRH
FGPRH
FWPRH
FLPRH
FVPRH

-- Production cumulatives
FOPT
FGPT
FWPT
FLPT
FVPT
FOPTH
FGPTH
FWPTH
FLPTH

-- Injection rates
FGIR
FWIR
FGIRH
FWIRH

-- Injection cumulatives
FGIT
FWIT
FGITH
FWITH

-- Ratios
FGOR
FWCT
FGORH
FWCTH

-- In-place volumes
FOIP
FGIP
FWIP

-- Pore volumes
FOPV
FGPV
FWPV
FRPV
FHPV

-- Pressure
FPR

-- Recovery Efficiency
FOE

-- Active wells
FMWPR
FMWIN

-- #######################
-- ## Region quantities ##
-- #######################

-- Pressure
RPR
/

-- In-place volumes
ROIP
/
RGIP
/
RWIP
/

-- #####################
-- ## Well quantities ##
-- #####################

-- Production rates
WOPR
/
WGPR
/
WWPR
/
WOPRH
/
WGPRH
/
WWPRH
/

-- Production cumulatives
WOPT
/
WGPT
/
WWPT
/
WOPTH
/
WGPTH
/
WWPTH
/

-- Injection rates
WGIR
/
WWIR
/
WGIRH
/
WWIRH
/

-- Injection cumulatives
WGIT
/
WWIT
/
WGITH
/
WWITH
/

-- Ratios
WGOR
/
WWCT
/
WGORH
/
WWCTH
/

-- Pressure
WBHP
/
WTHP
/
WBHPH
/
WTHPH
/
